### PR TITLE
Option to omit until part in humanreadable

### PR DESCRIPTION
**Pull request by ShoresOfNowhere**
I' thought it would be nice to have an option so that the "until" part of the rule could be omitted, in those cases when that information is shown elsewhere.

Bye!

### CODE REVIEW

**Comment by rlanvin** [comment]
Thank you for the PR, and apologies for the late reply, summer was a busy time! I agree it's a nice option to have but it should be `include_until` (default true) to be consistent with the other option `include_start`. Would you be able to update your PR? Otherwise I'll update it myself.

**Comment by ShoresOfNowhere** [comment]
Done! :)

**Comment by rlanvin** [comment]
Thank you!

**Comment by ShoresOfNowhere** [comment]
It was a pleasure, too many times contributions to projects here on github remain ignored!

**Pull request merged**
