### PR TITLE
Adding padding by zero to Hour:Minute in RRule.php

### PR DESCRIPTION
**Pull request by aminprox**
Just like the last merge but with the correct PSR.

### CODE REVIEW

**Comment by rlanvin** [comment]
@aminprox Thanks for the updated PR. FYI you could have amended the previous one, a bit less effort ;-)

So I have been reviewing and testing this, and I'm not sure exactly what problem you are trying to solve, or if it's the right way to solve it. In French for example the leading 0 would be grammatically incorrect, so your patch would not work. Can you give me an example of when the current generated sentence is incorrect?

**Comment by aminprox** [comment]
It's formal to have leading zero (or at least here it is).
Like 08:05 instead of 8:5 just like the 00:00 format for time.
So there should be an option for this maybe?

**Comment by rlanvin** [comment]
I agree with this, but this PR changes human readable sentences such as "repeats every hour at 8" to "repeat every hour at 08", which doesn't look correct to me (at least in some locales like French, it isn't). Can you provide a code that generates "8:5" instead of "08:05" so I can better understand where this behaviour is coming from?

**Comment by rlanvin** [comment]
@aminprox Ping

**Pull request closed without merging**
